@startuml

object Welcome
object "License Key Entry" as LicenseKeyEntry

object "Registration Form" as RegistrationForm
object Review
object Completed

Welcome -down-> LicenseKeyEntry

LicenseKeyEntry -right-> RegistrationForm : Next
RegistrationForm -left-> LicenseKeyEntry : Back

RegistrationForm -down-> Review : Next
Review -up-> RegistrationForm : Back

Review -> Completed : Register

@enduml